### ISSUE TITLE
Crash when starting automation (404 not found)

### ISSUE THREAD

**Issue by gr33nd3v1l** [imaboy321/Ledybot#10]
I have o3ds with a9lh and luma

I have NTR CFW 3.4 Preview5 and BootNTR 3.1, InputRedirection without mode3 but it seems to work fine.

These are the ones I installed, according to [this](https://www.reddit.com/r/Pokemongiveaway/comments/5ty9iz/how_to_install_ledybot_guide/) wonderful guide      
https://github.com/44670/BootNTR/releases    
https://github.com/Kazo/InputRedirection/releases    
https://github.com/imaboy321/Ledybot/releases    

My Ledybot connects fine, and reads manual trades over GTS, albeit very weirdly (http://i.imgur.com/F78sfQJ.png) - no I didn't trade Clarence 3x, or any Clarence at all.

It apparently belongs to /u/HikerClarence who did in fact post last in my giveaway thread. The bot was not set up to read reddit, and I didn't manually trade him.

And Ledybot won't trade automatically at all.

After making sure everything up to the automation was OK:

This is where I hit my first roadblock...

Same as before, after putting in reddit information from my thread [here](https://www.reddit.com/r/Pokemongiveaway/comments/5u1xtv/competitive_tapu_fini_giveaway/) I'm greeted with this error message

http://i.imgur.com/awf6kkr.png

    See the end of this message for details on invoking 
    just-in-time (JIT) debugging instead of this dialog box.
    
    ************** Exception Text **************
    System.Net.WebException: The remote server returned an error: (404) Not Found.
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
       at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
    
    
    ************** Loaded Assemblies **************
    mscorlib
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
    ----------------------------------------
    Ledybot
        Assembly Version: 1.0.0.0
        Win32 Version: 1.0.0.0
        CodeBase: file:///B:/PKMN/Ledybot/Ledybot.exe
    ----------------------------------------
    System.Windows.Forms
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    ----------------------------------------
    System
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.Drawing
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    ----------------------------------------
    System.Configuration
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    ----------------------------------------
    System.Core
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
    ----------------------------------------
    System.Xml
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
    ----------------------------------------
    System.Data
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
    ----------------------------------------
    System.Numerics
        Assembly Version: 4.0.0.0
        Win32 Version: 4.6.1590.0 built by: NETFXREL2
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
    ----------------------------------------
    Newtonsoft.Json
        Assembly Version: 9.0.0.0
        Win32 Version: 9.0.1.19813
        CodeBase: file:///B:/PKMN/Ledybot/Newtonsoft.Json.DLL
    ----------------------------------------
    
    ************** JIT Debugging **************
    To enable just-in-time (JIT) debugging, the .config file for this
    application or computer (machine.config) must have the
    jitDebugging value set in the system.windows.forms section.
    The application must also be compiled with debugging
    enabled.
    
    For example:
    
    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>
    
    When JIT debugging is enabled, any unhandled exception
    will be sent to the JIT debugger registered on the computer
    rather than be handled by this dialog box.
    
    
    

/u/gigaplexorax mentioned:
- Based on the error, Ledybot either couldn't connect to your 3DS or to Reddit. I imagine that retrying several times will fix the issue, but I'm no Ledybot expert

I concluded that much, but how come it can read that I've manually traded in that case. It says Connected! when I start it =\

____________________________________

I hope someone can be of some assistance, and I can be of some assistance to you.

I have no firewall that could be blocking traffic (windows firewall is off and NOD is set to allow)

- This was written hastily, I will be back tomorrow. Tired after almost whole day of trying to get this to work.

**Comment by SteveCookTU** [comment]
I see the issue. The reddit box just holds the ID of the thread such as 5u3tfp from https://www.reddit.com/r/PokemonPlaza/comments/5u3tfp/gen_7_dragonite_and_lucario_giveaway/. You can set the subreddit in the settings tab.

**Comment by gr33nd3v1l** [comment]
You are absolutely correct, and thank you!

In other news:
Could you make the window resizable?

And, new error:
```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Arrays larger than 2GB are not supported.
Parameter name: sourceIndex
   at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   at Ledybot.GTSBot7.<RunBot>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ledybot.MainForm.<btn_Start_Click>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Ledybot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///B:/PKMN/Ledybot/Ledybot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by SteveCookTU** [comment]
This error could depend on your setup. Are you on an O3DS?

**Comment by gr33nd3v1l** [comment]
Yes, o3ds - I posted what information I could in the top post

**Comment by gr33nd3v1l** [comment]
I'd just like to update a bit:

These were all manually traded, but it did read each time I traded, and halfway through it decided to change
http://i.imgur.com/36uSpSd.png

The Pokemon was in slot 1,1 of box 1. First it was Tapu Fini, then it was Tapu Lele
Tapu Fini was the 1st request in my thread, Tapu Lele was 2nd, and trainer names match
This leads me to believe that everything works up to the trading, and then something fails

And Injection works, so it means that there is a connection back and forth between the 3DS>PC

And here we go again.. This time it detected trades on its own (I can't know if it actually traded), after I ticked "Black List" and trying a few more times. (I didn't close Ledybot)

It wrote that it traded 3 guys, but spat out this. I guess you don't need the whole code, just the exception

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
```

************** Exception Text **************
System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   at Ledybot.GTSBot7.<RunBot>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ledybot.MainForm.<btn_Start_Click>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by gr33nd3v1l** [comment]
One more thing I discovered is:

The bot doesn't do anything on its own sometimes until I go to manual GTS search
At that point when I find a pokemon in the GTS that I click on to trade - the bot pops out a trainer from the reddit thread (usually the first poster) 
This happens at the moment when I click on the pokemon someone has deposited in GTS, but not always.

**Comment by gr33nd3v1l** [comment]
For anyone else that runs into these kinds of problems:

DOWNLOAD THE CORRECT INPUTREDIRECT_MODE3

https://github.com/Stary2001/InputRedirection/releases/tag/v1.2
