### ISSUE TITLE
Bot stuck at the front page

### ISSUE THREAD

**Issue by CuredOne** [imaboy321/Ledybot#12]
Currently the bot stays at the front page of the GTS and will only trade the first person it sees. It appears the search function does not work anymore. I've spoken to other members who enjoy the bot, to find out they are experiencing the same issue. The bot itself works well if they are the first result shown though.

**Comment by gr33nd3v1l** [comment]
It trades normally from back for me - is there a new version out?

**Comment by SteveCookTU** [comment]
The bot does not visibly move from deposit to deposit. If there are 100 on the page it goes to the next. If it goes back to the menu and researches it means no one meets the criteria to trade.

**Comment by CuredOne** [comment]
Apparently this was an isolated incident, as about 5 hours later it worked. The issue was it wouldn't move past the first deposit. It would exit, come back in and check the first (as i would check manually and about 3 down was the requested Pokemon), and then loop back to checking the first and exiting. I'm going to assume this was a problem on Nintendo's end, sorry about that.
