### ISSUE TITLE
Error occured before trade

### ISSUE THREAD

**Issue by Avalarion90** [imaboy321/Ledybot#19]
Every time the bot find someone to trade with i get an error in Ledybot: http://pastebin.com/wxvM7CNW

And the Game just closes with the error message an error has occurred forcing the software to close

**Comment by SteveCookTU** [comment]
I noticed your stacktrace was in german? Is your game language set to english?

**Comment by Avalarion90** [comment]
ok. everything works well if the game is in english ^^
