### ISSUE TITLE
How do nickname-specifics work

### ISSUE THREAD

**Issue by gr33nd3v1l** [imaboy321/Ledybot#23]
So today I tried adding Sawsbuck, all 4 formes

I named the .pk7 files: autumn, winter, spring, summer
I copied them in the folders created after dragging the files into Giveaway window, and left the files themselves where they were

Ledybot doesn't trade according to nicknames. Case specific didn't matter either

This was never explained anywhere, and I never found a Ditto bot setup, so I believe it works, I only got it set up bad

**Comment by KNYuki** [comment]
I'd suggest deleting the entries under "Specific path", that's what I did. I think with there being a specific path, the bot trades the original .pk7 file AND the ones in the folder, but with that field empty, the bot only trades the .pk7s in the folder thus only trading nicknames. Hope that helps.

**Comment by gr33nd3v1l** [comment]
for anyone ever wondering; this was my error entirely

My default Ditto (DITTO.pk7) is    
```
DOCI (Ditto) @ Destiny Knot
EVs: 252 HP / 6 Def / 252 Spe
Ability: Limber
Level: 99
Shiny: Yes
Docile Nature
- Transform
```
- this worked 
![](https://i.imgur.com/8vCWGnN.png)

folder inside is what nicknames it reads, default "ditto.pk7" dragged into ledybot, and the "ADAMANT.pk7" etc placed inside the created ditto folder
