### ISSUE TITLE
Bot Searches for the incorrect Pokemon in GTS

### ISSUE THREAD

**Issue by StonedModder** [imaboy321/Ledybot#3]
I am currently using the latest release of your bot and have tried to make it search for 2 pokemon. The first being a Caterpie which resulted in the bot searching for Zubat in the GTS and the second being a Zubat which results in the bot searching for Yungoose

**Comment by SteveCookTU** [comment]
When you start the bot, make sure everything is at the default position. In the box you should be at box 1 slot 1. If you go into the menu to search for a pokemon, make sure the pointer is at the letter A by default.

**Comment by StonedModder** [comment]
Thank you for the quick reply! That seems to have fixed it, There seems to one more issue however. After the bot "fails" a trade and also completes a trade it will then go to search for your pokemon again. In this case a caterpie however it gets stuck searching for an incorrect Pokemon since the failed trade seems to have moved the cursor somewhere else. Is there a way to reset this without exiting the GTS and starting the bot all over again?

**Comment by SteveCookTU** [comment]
When you say "fail" do you mean the pokemon was already traded or nothing was found?

**Comment by StonedModder** [comment]
By fail I'm referring to the system attempting to do a trade however the trade animation never begins on the 3DS. Since the 3ds can't select a "valid" pokemon.

i.e. The bot is trying to trade a mimikyu for caterpies. Whenever it is attempting a trade it gets stuck in my box 4 and tries to trade a comfey.

Which it will then fail since that isnt the correct pokemon and it will then get stuck in the menus again.

The odd part is. The bot is acting like these trades are being successful. I have attached an image of what Im referring too as successful. If you would like I can also get a screenshot of the trade screen that it gets stuck on before "failing"

I apologize if this isn't very clear. If it still isn't please let me know and I will be more then happy to elaborate
![wesjxkd](https://cloud.githubusercontent.com/assets/16449821/22621936/64e39772-eafd-11e6-8cfc-5d9b46863fcf.png)

**Comment by SteveCookTU** [comment]
Oh like I said make sure you start your box off in box 1. To do this you need to go into deposit, scroll to box 1, and back out.

**Comment by StonedModder** [comment]
I see. I apologize. I overlooked that portion.  Is there something else small that I missed since the bot isn't going past slot 1 in the box? I would like to assume so since this is all shaping up to be user error and I apologize

**Comment by SteveCookTU** [comment]
No need to apologize haha. The way the bot works is confusing. So the bot injects the pokemon into box 1 slot 1 every time it goes to trade. It will always use slot 1 for the trades and it always injects it as it goes to the box display when searching for players. As long as box 1 was the last box you were in it will trade properly. I will probably be making a text guide soon so users can follow it.

**Comment by StonedModder** [comment]
I see! Im on the same page now. 

If I may make a recommendation then, would you consider adding a setting at which we can change where the bot looks? i.e. box 8 slot 1

Its all working as intended now! If its okay with you I may make my own text tutorial for Se7enSins(with credit of course!)
