### ISSUE TITLE
Bot wont work Correctly

### ISSUE THREAD

**Issue by Bappsack** [imaboy321/Ledybot#34]
Everytime i start the Bot he search for Pokemon and sometimes he stops and doesnt work again, my internet connection on N3DS XL is broken and i have to restart the whole console.
i got sometimes a over 2GB Error or an other Error "Cant be NULL".

**Comment by PumPum7** [comment]
Have the same problem. Hope it gets fixed

**Comment by Bappsack** [comment]
I got it fixed but not 100%
I saw that Ledybot use a high network traffic so the 3ds cant handle it.
My Way:

Do a Hotspot on Windows 10 and Login with your 3ds to the Hotspot and place the 3ds near to the Laptop/Pc. im using NTR 3.4 Preview too now.
Works much better then before! 80% error less now :)

**Comment by PumPum7** [comment]
Will try it. I Use NTR 3.5 and i have two different WLANs in my PC and my 3DS. One 5GHZ and one 2,4 GHZ

**Comment by Bappsack** [comment]
good luck :)
