### ISSUE TITLE
Bot crashing error inside post

### ISSUE THREAD

**Issue by stratosfeargaming** [imaboy321/Ledybot#38]
crash because error makes this crash Object name: 'System.Net.Sockets.NetworkStream'.

**Comment by stratosfeargaming** [comment]
any1???

**Comment by Lucaber** [comment]
Is your game in English?

**Comment by stratosfeargaming** [comment]
yes

**Comment by Bappsack** [comment]
poor Network connection

**Comment by SteveCookTU** [comment]
This usually happens when the network connection isn't strong enough and can't keep up with the commands from the bot.
