### ISSUE TITLE
Bot not trading

### ISSUE THREAD

**Issue by KNYuki** [imaboy321/Ledybot#4]
Me again lol. I just started using the new updated version and the bot searches as intended but doesn't seem to be trading anyone.  It just keeps searching then exiting from the screen then going back in again to search. Same thing for a couple minutes with no trade going on. 

Also a suggestion: is it possible to have the list show pokemon name instead of their dex number? Or at least allow us to input Pokemon names instead or alongside their dex. Thanks!

**Comment by SteveCookTU** [comment]
I haven't touched anything with the trading with the last couple updates. If it is exiting and then re-searching then there is no one asking for what you are giving away. Stuff like nicknames have to be exact and you have to make sure the files exist. Double check your giveaway settings to make sure everything is set up properly.

**Comment by KNYuki** [comment]
Just figured out why it wasn't trading. New update had reddit checked when I first opened it lol.  Thanks anyway!
