### ISSUE TITLE
Can you use Ladybot on Old 3ds?

### ISSUE THREAD

**Issue by Terax235** [imaboy321/Ledybot#40]
I want to use Ledybot on my Old 3ds!
Is that possible or not? (I already have NTR and InputRedirection)

**Comment by ghost** [comment]
Should be possible. You only can't stream the bot trading with people through NTRViewer so far I know.

**Comment by Terax235** [comment]
ok thx for your help :D

**Comment by ghost** [comment]
Seems I've mistake in that claim after checking a certain reddit post.
Guess Old 3DS users are out of luck. :c

**Comment by SteveCookTU** [comment]
The only way it will work is if the debugger is enabled on the Old 3DS. If the device is unable to launch with debug mode on NTR, then I don't believe it will work at instructed.
