### ISSUE TITLE
Release 2.3 - Unstable

### ISSUE THREAD

**Issue by ghost** [imaboy321/Ledybot#7]
This release will desync / mess up commands after 3-4 trades.
With version 2.2 I'm able to do 150+ trades without errors.

**Comment by ghost** [comment]
Desync happens because after injecting a .pk7 ledybot clicks "A" the first time to select the pokémon, but then fails to click "A" a second time to confirm the trade. After that it desyncs

**Comment by ghost** [comment]
**Update: Attempting to trade a pokémon holding a Z-Crystal will cause a desync**

**Comment by SteveCookTU** [comment]
The z-crystal thing should have been obvious since you cannot GTS them and megastones. Also, the latest update did not interfere with the timing of the trades so any 'desyncs' related to the timing of button presses would because of any sort of interruption of the wireless signal.

**Comment by ghost** [comment]
Wouldn't it be a good idea to just add an extra "A" click input after the first two when selecting the pokémon? This would add mega stone and z-crystal compatibility so users wouldn't have to worry about it

**Comment by SteveCookTU** [comment]
I would but then it wouldn't come to your attention that you aren't even giving away one of the pokemon on your list.
