### ISSUE TITLE
Mass import skips files

### ISSUE THREAD

**Issue by KNYuki** [imaboy321/Ledybot#8]
Something I've been realizing the last few days is that mass importing doesn't actually import every pk7 file in the folder? Say I drag a folder of 10 pk7 files, so 10 pokemon, but only 8 pokemon appears in the giveaway details.  This becomes an easily overlooked problem if I'm importing bigger batches of files.  I think if anything, it'll be helpful to have entries numbered so at least we can know if the numbers don't match up.

**Comment by SteveCookTU** [comment]
If the files are the same pokemon species it will only add the first instance of it. For multiple pokemon of the same species, place them inside the "specific/optional folder" created with each pk7 added.

**Comment by KNYuki** [comment]
They are different though? I keep all duplicate instances of pokemon, like different forms in its own folder. To draw a clear picture, say I'm importing pk7s of latios, latias, arcanine, venusaur, mimikyu, dhelmise and tyrantrum in a batch folder, but only arcanine and venusaur gets added in.

**Comment by SteveCookTU** [comment]
A batch folder? If you aren't on windows that could be an issue. Linux might not be 100% supported. It would only skip if something on the file was invalid. I can easily mass import 190 at a time.

**Comment by KNYuki** [comment]
Yeah, all my pk7s have been in a single folder. Funny thing is I'm on windows too, but whenever I try to import 60 pokemon at a time, at least a third will be missed and I don't find out until people point out that pokemon haven't been traded and that's because the pk7 wasn't imported in the first place.

**Comment by SteveCookTU** [comment]
Please provide a zip file of all your pk7s so I can test them.

**Comment by KNYuki** [comment]
https://www.dropbox.com/s/mt80w3j4sspa7js/Main%20Batch.rar?dl=0

There's the link

**Comment by SteveCookTU** [comment]
Ok so I just got around to finding the issue and it was actually pretty funny. Some of the files within the folder are actually .bak files. There are 18 .bak files which can't be loaded and is why only 69 of them load.

**Comment by KNYuki** [comment]
I get that .bak files will not import. Should i assume that without the .bak files in the folder, the associated pk7 files will be imported as intended? Because I'm still having the same issues so far.

**Comment by SteveCookTU** [comment]
No need to assume because all the pk7s are importing. With your collection you gave me, 18 of the files were baks. With a total of 87 files only 69 imported. The ones missing were the .baks

**Comment by KNYuki** [comment]
Very odd then because I'm still facing the same problem with a new batch folder of .pk7s, there were still missing entries when drag-dropping and they weren't the baks. Couldn't find out which .pk7s they were until people reported which pokemon weren't trading; upon checking the ones not trading were actual .pk7s (not .baks) in the batch folder that never imported. :/

**Comment by gr33nd3v1l** [comment]
I've actually had this happen to me too. No idea why and how it happens

**Comment by SteveCookTU** [comment]
If possible send me the latest batch so I can test and attempt to replicate the issue.

**Comment by gr33nd3v1l** [comment]
I've deleted the ones that did it by now, but I'll leave a mental note for the next time it happens

**Comment by KNYuki** [comment]
Found out that .bak files weren't the problem. But if I were to (accidentally) have duplicate .pk7s of the same pokemon, even with different names, the import will be cut off.  I've been importing in smaller batches and haven't had the problem so far, but I'll report back if it happens again.
