### ISSUE TITLE
Update the blacklist and how it works if possible

### ISSUE THREAD

**Issue by Naturally-Delicious** [imaboy321/Ledybot#9]
I'm trying to give out multiple Pokemon via the bot. Let me show an example. Let's say I'm giving out Squirtle, Charmander and Bulbasaur. Person A deposits a Pokemon to get Squirtle. The bot trades Person A then adds them to the black list so that person can't abuse the bot to get more than one Squirtle. The thing is with the current blacklist is that it prevents the person from being able to get Charmander and Bulbasaur since the bot will skip over them when they deposit another Pokemon for the other two. Are you able to change how the blacklist, so that it prevents someone from getting more than one Squirtle BUT, still allows them to get Charmander and Bulbasaur? Hopefully I explained this well...

**Comment by SteveCookTU** [comment]
Right now each pokemon has it's own blacklist. They are able to get one of everything given away. In this giveaway blacklist is enabled and users are able to obtain one of each: https://docs.google.com/spreadsheets/d/1wQVv9vA_EFpUtwOnw1Y478zqWU33Homgyc-YOujWfng/edit?usp=sharing

**Comment by Naturally-Delicious** [comment]
Are you sure? People in my giveaway have been saying the bot hasn't been trading them after their 1st request.

**Comment by SteveCookTU** [comment]
It does for me and a lot of others. Unless you have a very old version they each have their own.
